import { Metadata } from "next";
import { Providers } from "./providers";
import Header from "./Header";
import Footer from "./Footer";

export const metadata: Metadata = {
  title: "Find Recipe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
